version: '3'
services:
  todofront:
    image: todofrontend
    environment:
     - REACT_APP_API_HOST=todoback
    ports:
     - 3000:3000
    depends_on:
     - todoback
  todoback:
    image: todobackend
    ports:
     - 3001:3001
  todotests:
    image: todotests
    environment:
     - FRONT_HOST=frontend
    depends_on:
     - todoback
     - todofront